name       : perl-file-slurper
version    : '0.013'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/File-Slurper-0.013.tar.gz : e2f6a4029a6a242d50054044f1fb86770b9b5cc4daeb1a967f91ffb42716a8c5
homepage   : https://metacpan.org/pod/File::Slurper
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Slurper - A simple, sane and efficient module to slurp a file
description: |
    This module provides functions for fast and correct slurping and spewing. All functions are optionally exported. All functions throw exceptions on errors, write functions don't return any meaningful value.
builddeps  :
    - perl-test-warnings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
