name       : perl-file-slurper
version    : '0.014'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/File-Slurper-0.014.tar.gz : d5a36487339888c3cd758e648160ee1d70eb4153cacbaff57846dbcefb344b0c
homepage   : https://metacpan.org/pod/File::Slurper
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Slurper - A simple, sane and efficient module to slurp a file
description: |
    This module provides functions for fast and correct slurping and spewing. All functions are optionally exported. All functions throw exceptions on errors, write functions don't return any meaningful value.
builddeps  :
    - perl-test-warnings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
